version: 2.1

jobs:
  qa:
    docker:
      - image: cimg/node:24.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-front-npm-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-front-npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build

workflows:
  qa:
    jobs:
      - qa
